name: CI
on: [pull_request, push]
env:
    GEMINI_API_KEY: ${{secrets.GEMINI_API_KEY}}
    DATABASE_URL: "postgresql://dummy_user:dummy_pass@localhost:5432/dummy_db" # <-- Bura diqqət!
run: |
    pytest tests/ --cov=src --cov-report=term-missing
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - run: pip install -r requirements.txt
      - run: pip install pytest-cov
      - name: Test
        run: pytest tests/ --cov=src --cov-report=term-missing
      - name: Docker build test
        run: docker build -t finalproj .
